baseurl = "https://schlawiner.github.io/fu-rpg-frei-und-universell/"
languageCode = "de-de"
title = "FU - Frei und universell"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	#author = ""
	 description = "Deutsche Übersetzung des Rollenspiels Freeform Universal (FU)."
	 copyright = "Creative Commons Attribution 3.0 Unported "

	# Repository
	#   provider = "GitHub"
	#  repo_url = "https://github.com/schlawiner/fu-rpg-frei-und-universell"

	version = "0.2"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [
		"stylesheets/custom_style.css"
	]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent  = "cyan"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	# twitter = "apfeleimer"
	# github  = "schlawiner"


# [[menu.main]]
# 	name   = "FU - Frei und universell"
# 	url    = "/"
# 	weight = 0

[[menu.main]]
	name   = "Einleitung"
	url    = "01-einleitung/"
	weight = 10

[[menu.main]]
	name   = "Die Grundlagen"
	url    = "02-grundlagen/"
	weight = 20

[[menu.main]]
	name   = "Die Figuren"
	url    = "03-figuren/"
	weight = 30

[[menu.main]]
	name   = "Etwas tun"
	url    = "04-handeln/"
	weight = 40

[[menu.main]]
	name   = "Die Erzählerin"
	url    = "05-erzaehlerin/"
	weight = 50

[[menu.main]]
	name   = "Beispielabenteuer: Rennen zum Tempel des Toth"
	url    = "06-rennen-zum-tempel/"
	weight = 60

[[menu.main]]
	name   = "Anhang"
	url    = "07-anhang/"
	weight = 70

	[[menu.main]]
		name   = "[Impressum]"
		url    = "impressum"
		weight = 100




[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
