baseurl = "https://fu-rollenspiel.de/"
# baseurl = "https://schlawiner.github.io/fu-rpg-frei-und-universell/"
languageCode = "de-de"
title = "FU: Das freie und universelle Rollenspiel"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-77950074-2"
Paginate = 4
disqusShortname = "fu-rollenspiel"

[params]
	# General information
	#author = ""
	 description = "Deutsche Übersetzung des Rollenspiels Freeform Universal (FU)."
	 copyright = "Creative Commons Attribution 3.0 Unported"

	# Repository
	#   provider = "GitHub"
	#  repo_url = "https://github.com/schlawiner/fu-rpg-frei-und-universell"

	version = "1.0"
	logo = "images/logo.png"
	favicon = "favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom_style.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	# language
	defaultContentLanguage =  "de"

	[params.palette]
	# primary = "light-blue"
	# accent  = "cyan"
  # primary = "light-green"
  # accent  = "light-green"
	primary = "light-green"
	accent  = "orange"

    [params.font]
    	# text = "Ubuntu"
			text = "Arvo"
		 headers = "Cardenio Modern Bold"
    	code = "Ubuntu Mono"


[social]
	# twitter = "apfeleimer"
	# github  = "schlawiner"


# [[menu.main]]
# 	name   = "FU - Frei und universell"
# 	url    = "/"
# 	weight = 0

[[menu.main]]
	name = "Blog"
	url = "blog/"
	weight=9

[[menu.main]]
	name   = "1. Einleitung"
	url    = "01-einleitung/"
	weight = 10

[[menu.main]]
	name   = "2. Die Grundlagen"
	url    = "02-grundlagen/"
	weight = 20

[[menu.main]]
	name   = "3. Die Figuren"
	url    = "03-figuren/"
	weight = 30

[[menu.main]]
	name   = "4. Etwas tun"
	url    = "04-handeln/"
	weight = 40

[[menu.main]]
	name   = "5. Die Erzählerin"
	url    = "05-erzaehlerin/"
	weight = 50

[[menu.main]]
	name   = "6. Beispielabenteuer: Rennen zum Tempel des Toth"
	url    = "06-rennen-zum-tempel/"
	weight = 60

[[menu.main]]
	name   = "7. Anhang"
	url    = "07-anhang/"
	weight = 70

	[[menu.main]]
		name   = "8. Downloads"
		url    = "08-downloads/"
		weight = 70

	[[menu.main]]
		name   = "[Impressum]"
		url    = "impressum"
		weight = 100




[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
